# learning_resources.py

learning_links = {
    # IT / Programming Languages & Frameworks
    "django": "https://www.djangoproject.com/start/",
    "aws": "https://aws.amazon.com/training/",
    "react.js": "https://reactjs.org/docs/getting-started.html",
    "flask": "https://flask.palletsprojects.com/en/2.3.x/tutorial/",
    "python": "https://docs.python.org/3/tutorial/",
    "docker": "https://docker-curriculum.com/",
    "kubernetes": "https://kubernetes.io/docs/tutorials/",
    "sql": "https://www.w3schools.com/sql/",
    "git": "https://learngitbranching.js.org/",
    "linux": "https://linuxjourney.com/",
    "html": "https://developer.mozilla.org/en-US/docs/Learn/HTML",
    "css": "https://developer.mozilla.org/en-US/docs/Learn/CSS",
    "javascript": "https://javascript.info/",
    "node.js": "https://nodejs.dev/en/learn/",
    "mongodb": "https://www.mongodb.com/learn",
    "postgresql": "https://www.postgresqltutorial.com/",
    "typescript": "https://www.typescriptlang.org/docs/",
    "c++": "https://www.cplusplus.com/doc/tutorial/",
    "java": "https://www.oracle.com/java/technologies/javase/tutorial/",
    "c#": "https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/",
    "php": "https://www.php.net/manual/en/tutorial.php",
    "ruby": "https://www.ruby-lang.org/en/documentation/quickstart/",
    "swift": "https://swift.org/documentation/#the-swift-programming-language",
    "tensorflow": "https://www.tensorflow.org/tutorials",
    "pytorch": "https://pytorch.org/tutorials/",
    "machine learning": "https://www.coursera.org/learn/machine-learning",
    "deep learning": "https://www.deeplearning.ai/deep-learning-specialization/",
    "nlp": "https://nlp.stanford.edu/courses/CS224n/",
    "rest api": "https://restfulapi.net/",
    "graphql": "https://graphql.org/learn/",
    "ci/cd": "https://www.redhat.com/en/topics/devops/what-is-ci-cd",
    "jenkins": "https://www.jenkins.io/doc/tutorials/",
    "firebase": "https://firebase.google.com/docs",
    "azure": "https://docs.microsoft.com/en-us/learn/azure/",
    "gcp": "https://cloud.google.com/training",
    "heroku": "https://devcenter.heroku.com/start",
    "netlify": "https://docs.netlify.com/",
    "bootstrap": "https://getbootstrap.com/docs/5.0/getting-started/introduction/",
    "tailwind": "https://tailwindcss.com/docs",
    "angular": "https://angular.io/start",
    "vue.js": "https://vuejs.org/v2/guide/",
    "express.js": "https://expressjs.com/en/starter/installing.html",
    "fastapi": "https://fastapi.tiangolo.com/tutorial/",
    "spring": "https://spring.io/guides",
    "springboot": "https://spring.io/projects/spring-boot",
    "intellij": "https://www.jetbrains.com/idea/guide/tutorials/",
    "pycharm": "https://www.jetbrains.com/pycharm/learn/",
    "vs code": "https://code.visualstudio.com/docs",
    "jira": "https://www.atlassian.com/software/jira/guides",
    "postman": "https://learning.postman.com/docs/getting-started/introduction/",
    "gitlab": "https://docs.gitlab.com/ee/gitlab-basics/",
    "bitbucket": "https://bitbucket.org/product/guides",
    "numpy": "https://numpy.org/devdocs/user/quickstart.html",
    "pandas": "https://pandas.pydata.org/docs/getting_started/index.html",
    "matplotlib": "https://matplotlib.org/stable/tutorials/index.html",
    "seaborn": "https://seaborn.pydata.org/tutorial.html",
    "scikit-learn": "https://scikit-learn.org/stable/tutorial/index.html",
    "openai": "https://platform.openai.com/docs/tutorials",
    "huggingface": "https://huggingface.co/transformers/quickstart.html",
    "unix": "https://www.udemy.com/course/unix-linux-command-line-for-beginners/",
    "bash": "https://ryanstutorials.net/bash-scripting-tutorial/",
    "api": "https://restfulapi.net/",
    "oop": "https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/",
    "mvc": "https://www.tutorialspoint.com/mvc_framework/mvc_framework_introduction.htm",
    "unit testing": "https://realpython.com/python-testing/",
    "integration testing": "https://www.guru99.com/integration-testing.html",

    # Soft Skills
    "communication": "https://www.coursera.org/learn/communication-skills",
    "teamwork": "https://www.coursera.org/learn/teamwork-skills",
    "problem-solving": "https://www.edx.org/course/problem-solving",
    "leadership": "https://www.coursera.org/specializations/leadership-skills",
    "collaboration": "https://www.linkedin.com/learning/collaboration-principles-and-processes",
    "adaptability": "https://www.mindtools.com/pages/article/adaptability.htm",
    "critical thinking": "https://www.edx.org/course/critical-thinking-skills-for-university-success",
    "time management": "https://www.coursera.org/learn/work-smarter-not-harder",
    "attention to detail": "https://www.skillshare.com/classes/Attention-to-Detail-Masterclass/1594591251",
    "learning": "https://www.edx.org/course/how-to-learn",
    "creativity": "https://www.coursera.org/learn/creativity-problem-solving",
    "decision making": "https://www.coursera.org/learn/decision-making",
    "conflict resolution": "https://www.udemy.com/course/conflict-resolution-skills/",
    "empathy": "https://www.psychologytoday.com/us/basics/empathy",

    # ECE (Electronics and Communication Engineering)
    "microcontrollers": "https://www.tutorialspoint.com/microcontroller/index.htm",
    "embedded systems": "https://www.coursera.org/specializations/embedded-systems",
    "signal processing": "https://www.coursera.org/learn/dsp",
    "digital electronics": "https://www.nptel.ac.in/courses/117/106/117106109/",
    "analog electronics": "https://www.electronics-tutorials.ws/analog/analog_1.html",
    "vlsi": "https://nptel.ac.in/courses/117/105/117105094/",
    "communication systems": "https://www.coursera.org/learn/communication-systems",
    "antenna design": "https://nptel.ac.in/courses/117/106/117106117/",
    "network theory": "https://nptel.ac.in/courses/117/103/117103028/",
    "control systems": "https://nptel.ac.in/courses/108/101/108101087/",

    # EEE (Electrical and Electronics Engineering)
    "power systems": "https://nptel.ac.in/courses/108/104/108104087/",
    "electric machines": "https://nptel.ac.in/courses/108/102/108102083/",
    "control engineering": "https://nptel.ac.in/courses/108/101/108101087/",
    "renewable energy": "https://www.coursera.org/learn/renewable-energy",
    "circuit analysis": "https://www.khanacademy.org/science/electrical-engineering",
    "electrical measurements": "https://nptel.ac.in/courses/108/105/108105085/",
    "power electronics": "https://nptel.ac.in/courses/108/105/108105086/",

    # Mechanical Engineering (optional)
    "thermodynamics": "https://nptel.ac.in/courses/112/105/112105149/",
    "fluid mechanics": "https://nptel.ac.in/courses/112/104/112104163/",
    "solid mechanics": "https://nptel.ac.in/courses/112/106/112106152/",
    "manufacturing processes": "https://nptel.ac.in/courses/112/102/112102082/",

    # Data Science / Analytics
    "data analysis": "https://www.datacamp.com/courses/data-analysis-in-python",
    "data visualization": "https://www.coursera.org/learn/datavisualization",
    "big data": "https://www.coursera.org/learn/big-data-analysis",
    "sql analytics": "https://mode.com/sql-tutorial/",
    "business intelligence": "https://www.tableau.com/learn/training",
}

